Update send route
Solidform-labs/newsletter pull request #14
Opened 2024-05-11 19:52 UTC by fBravoBravo

Make the send email to subscriber and send email to all subscribers just one function that accepts and array as body

2024-05-12 07:45 UTC, n4xo-dev requested changes

2024-05-12 07:45 UTC, n4xo-dev commented on internal/app/newsletter/api/controllers/newsletter.go
>  			"error": "id is required",
Inadequate error message

2024-05-12 07:45 UTC, n4xo-dev commented on internal/app/newsletter/api/routers/routes.go
> +	subs.Post("/send/:id", controllers.SendEmailToSubscribers)
`:id` is unnecessary and unused.

2024-05-12 08:01 UTC, fBravoBravo commented on internal/app/newsletter/api/controllers/newsletter.go
>  			"error": "id is required",
done

2024-05-19 09:43 UTC, betterAvoka24 commented
@fBravoBravo add swagger comments on top of function for documentation

2024-05-20 17:56 UTC, fBravoBravo commented
swagger docs added

2024-05-20 17:57 UTC, fBravoBravo commented
@n4xo-dev could you review the swagger docs? there are some parts that I don't know well, don't know if it's correct

2024-05-21 22:48 UTC, n4xo-dev approved these changes

2024-05-21 22:48 UTC, merged